CREATE TABLE IF NOT EXISTS DOMICILIO (
    DOMICILIOID INT PRIMARY KEY AUTO_INCREMENT,
    CALLE VARCHAR(255),
    NUMERO INT,
    LOCALIDAD VARCHAR(255),
    PROVINCIA VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PACIENTE (
    PACIENTEID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    DNI VARCHAR(255) UNIQUE,
    FECHAINGRESO DATE,
    DOMICILIOID INT NOT NULL,
    FOREIGN KEY (DOMICILIOID) REFERENCES DOMICILIO(DOMICILIOID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ODONTOLOGO (
    ODONTOLOGOID INT PRIMARY KEY AUTO_INCREMENT,
    NUMEROMATRICULA VARCHAR(50) NOT NULL UNIQUE,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL
);
